-- EN UN SISTEMA DE GESTIÓN DE VENTAS, TIENES LAS TABLAS VENTAS Y VENDEDORES. IMPLEMENTASTE UN TRIGGER QUE AUTOMÁTICAMENTE CALCULA Y ACTUALIZA EL TOTAL DE VENTAS DE UN VENDEDOR EN LA TABLA VENDEDORES CADA VEZ QUE SE REGISTRA UNA NUEVA VENTA EN LA TABLA VENTAS. PARA HACER ESTO, EL TRIGGER SE ACTIVA DESPUÉS DE CADA INSERCIÓN EN LA TABLA VENTAS Y SUMA TODOS LOS MONTOS DE LAS VENTAS DEL VENDEDOR CORRESPONDIENTE EN LA TABLA VENTAS, ACTUALIZANDO EL TOTAL EN LA TABLA VENDEDORES.
-- DADO ESTE ESCENARIO Y EL TRIGGER. ¿ES CIERTO QUE ESTE ENFOQUE ES EL MÁS EFICIENTE PARA MANTENER ACTUALIZADO EL TOTAL DE VENTAS DE CADA VENDEDOR? Respuesta: no, no es lo mas eficiente.

--EFICIENTE
CREATE OR REPLACE TRIGGER trg_recalcular_ventas
AFTER INSERT ON ventas
FOR EACH ROW
BEGIN
  UPDATE vendedores
  SET total_ventas = NVL(total_ventas, 0) + :NEW.monto
  WHERE vendedor_id = :NEW.vendedor_id;
END;
/


-- METODO INEFICIENTE
CREATE OR REPLACE TRIGGER trg_recalcular_ventas AFTER
    INSERT ON ventas FOR EACH ROW
DECLARE
    v_total DECIMAL(10, 2);
BEGIN
    SELECT
        sum(monto) INTO v_total
    FROM
        ventas
    WHERE
        vendedor_id = :new.vendedor_id;
    UPDATE vendedores
    SET
        total_ventas = v_total
    WHERE
        vendedor_id = :new.vendedor_id;
END;
/

